version: "3.9"

services:
  database:
    image: postgres
    container_name: database_spos
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=spos
      - POSTGRES_PASSWORD=spostodo
      - POSTGRES_DB=spos
    volumes:
      - pgspos:/data/postgres
  
  app:
    build: .
    container_name: node_spos
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgspos:
    driver: local
  